### ISSUE TITLE
update SAMD51 deets

### ISSUE THREAD

**Issue by ladyada** [PaulStoffregen/CoreMark#2]
hiya, the teensy 3.2 speed listing (218.26) is with 96MHz overclock/faster compile-time settings. If you were to pick "smaller" code and "72MHz" its `Iterations/Sec   : 126.76`

To have a comparable SAMD51 measurement, please select 180MHz overclock/'faster' compile flags, which is `Iterations/Sec   : 458.19` or 200MHz/"dragons" for `Iterations/Sec   : 536.35`

I'll submit a PR as well!

**Comment by PaulStoffregen** [comment]
Yeah, as the table expands with more results, probably best to add few columns for CPU type, clock speed, whether the speed is standard or overclocked.  On our forum some folks are already talking about altering compiler flags, which adds a whole 'nother dimension of complexity.

So far, I only ran each board with its default settings, and only the ones that are on my desk.

**Comment by ladyada** [comment]
totally understand - we're very conservative with initial settings but the SAMD51 is very happy to be overclocked just like the teensy 3.2 which is why we have the dropdowns :)

https://learn.adafruit.com/introducing-adafruit-itsybitsy-m4/adapting-sketches-to-m0#m4-performance-options-7-20

**Comment by PaulStoffregen** [comment]
The other interesting thing about SAMD51 is how differently it performs on the digital signature test.  So far I haven't looked into which of CoreMark's 3 tests are doing better or worse on various chips.  The CoreMark code comes with pretty strong guidelines not to modify anything other than the "portme" files, and even in those you're only supposed to do pretty specific things so as not to taint the benchmark.  Not sure if there's a way to get that info without editing those other files.

**Comment by ladyada** [comment]
yah not sure, i just ran the sketch as-is
