### ISSUE TITLE
Drhystone/CoreMark Benchmark on Arduino Leonardo 

### ISSUE THREAD

**Issue by denissin** [PaulStoffregen/CoreMark#7]
Hello Paul, I would like to test your Benchmarkcode on the Arduino Leonardo. 
Is this code also compatible to the Arduino Leonardo? 
Thank you for your support! 

![image](https://user-images.githubusercontent.com/55690516/65415614-65230d00-ddf6-11e9-8131-3f1607e3526c.png)

**Comment by denissin** [comment]
Because I'am not getting any Information/Paramters back.

**Comment by PaulStoffregen** [comment]
No.  CoreMark requires more than 2.5K RAM.
